---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-kube-vip
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: kube-vip
  interval: 30m
  path: ./kubernetes/apps/kube-system/kube-vip/app
  prune: false
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  targetNamespace: kube-system
  timeout: 5m
  wait: false
