---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: s3-mirror
  namespace: default
spec:
  schedule: "21 5,17 * * *"
  suspend: false
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 43200
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: rclone
              image: rclone/rclone:1.69.0
              env:
                - name: RCLONE_LOG_LEVEL
                  value: NOTICE
                - name: RCLONE_PROGRESS
                  value: "true"
                # - name: RCLONE_STATS_ONE_LINE
                #   value: "true"
                - name: RCLONE_STATS
                  value: 30s
                - name: RCLONE_FAST_LIST
                  value: "true"
                - name: RCLONE_CONFIG
                  value: "/config/rclone.conf"
              envFrom:
                - secretRef:
                    name: s3-mirror-secret
              command:
                - /bin/sh
                - -c
                - >-
                  wget -qO- -t 5 -T 10 https://hc-ping.com/$(HC_UUID)/start ;
                  rclone sync minio:longhorn backblaze-crypt-longhorn: &&
                  rclone sync minio:cloudnativepg backblaze-crypt-cnpg: &&
                  wget -qO- -t 5 -T 10 https://hc-ping.com/$(HC_UUID)
                # rclone sync minio:longhorn r2-crypt-longhorn: &&
                # rclone sync minio:cloudnativepg r2-crypt-cnpg: &&
              volumeMounts:
                - name: conf
                  mountPath: /config
                  readOnly: true
          volumes:
            - name: conf
              secret:
                secretName: s3-mirror-secret
                items:
                  - key: rclone.conf
                    path: rclone.conf
