---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-mirror-secret
  namespace: default
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    template:
      data:
        HC_UUID: "{{ .HC_UUID_S3_MIRROR }}"
        rclone.conf: |
          [minio]
          type = s3
          provider = Minio
          access_key_id = {{ .MINIO_CRONJOB_USER }}
          secret_access_key = {{ .MINIO_CRONJOB_PASS }}
          endpoint = http://{{ .MINIO_HOST }}

          [backblaze-longhorn]
          type = b2
          account = {{ .B2_CRONJOB_USER_LONGHORN }}
          key = {{ .B2_CRONJOB_PASS_LONGHORN }}
          hard_delete = true

          [backblaze-crypt-longhorn]
          type = crypt
          remote = backblaze-longhorn:{{ .B2_LONGHORN_BUCKET }}
          filename_encryption = off
          directory_name_encryption = false
          password = {{ .BACKBLAZE_CRYPT_PASS }}
          password2 = {{ .BACKBLAZE_CRYPT_PASS2 }}

          [backblaze-cnpg]
          type = b2
          account = {{ .B2_CRONJOB_USER_CNPG }}
          key = {{ .B2_CRONJOB_PASS_CNPG }}
          hard_delete = true

          [backblaze-crypt-cnpg]
          type = crypt
          remote = backblaze-cnpg:{{ .B2_CNPG_BUCKET }}
          filename_encryption = off
          directory_name_encryption = false
          password = {{ .BACKBLAZE_CRYPT_PASS }}
          password2 = {{ .BACKBLAZE_CRYPT_PASS2 }}

          [r2]
          type = s3
          provider = Cloudflare
          access_key_id = {{ .R2_CRONJOB_USER }}
          secret_access_key = {{ .R2_CRONJOB_PASS }}
          endpoint = {{ .R2_CRONJOB_ENDPOINT }}

          [r2-crypt-longhorn]
          type = crypt
          remote = r2:longhorn
          filename_encryption = off
          directory_name_encryption = false
          password = {{ .RCLONE_R2_CRYPT_PASS }}
          password2 = {{ .RCLONE_R2_CRYPT_PASS2 }}

          [r2-crypt-cnpg]
          type = crypt
          remote = r2:cnpg
          filename_encryption = off
          directory_name_encryption = false
          password = {{ .RCLONE_R2_CRYPT_PASS }}
          password2 = {{ .RCLONE_R2_CRYPT_PASS2 }}
  dataFrom:
    - extract:
        key: MINIO
    - extract:
        key: BACKBLAZE
    - extract:
        key: RCLONE_BACKUP
    - extract:
        key: HEALTHCHECKS
    - extract:
        key: CLOUDFLARE_R2
