---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./external-secrets/ks.yaml
  - ./intel-device-plugin/ks.yaml
  - ./kube-vip/ks.yaml
  - ./metrics-server/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./openebs/ks.yaml
  - ./reloader/ks.yaml
  - ./snapshot-controller/ks.yaml
