---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: database
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: redis
      version: 20.6.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    enabled: true
    architecture: standalone
    auth:
      enabled: true
      existingSecret: redis-ext
      existingSecretPasswordKey: password
    master:
      persistence:
        enabled: true
        existingClaim: redis-data
    commonConfiguration: |-
      # Enable AOF https://redis.io/topics/persistence#append-only-file
      appendonly yes
      # Disable RDB persistence, AOF persistence already enabled.
      save ""
      # Increase databases count
      databases 32
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m

