---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netshoot
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      netshoot:
        containers:
          app:
            image:
              repository: docker.io/nicolaka/netshoot
              tag: v0.16
            command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
                  - NET_RAW
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"vlan60",
                "namespace": "networking",
                "ips": ["192.168.60.210/24"]
              }]
