---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mosquitto
spec:
  sourcePVC: mosquitto-data
  trigger:
    schedule: "0 * * * *"
  restic:
    repository: mosquitto-volsync-secret
    pruneIntervalDays: 7
    retain:
      hourly: 24
      daily: 7
      weekly: 4
    copyMethod: Snapshot
    cacheStorageClassName: longhorn-cache
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: longhorn-cache
    volumeSnapshotClassName: longhorn-snapshot
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
