---
# Area
- name: area/ansible
  color: "72ccf3"
- name: area/github
  color: "72ccf3"
- name: area/kubernetes
  color: "72ccf3"
- name: area/pulumi
  color: "72ccf3"
# Renovate
- name: renovate/ansible
  color: "ffc300"
- name: renovate/container
  color: "ffc300"
- name: renovate/github-action
  color: "ffc300"
- name: renovate/github-release
  color: "ffc300"
- name: renovate/helm
  color: "ffc300"
- name: renovate/npm
  color: "ffc300"
# Semantic Type
- name: type/digest
  color: "ffec19"
- name: type/patch
  color: "ffec19"
- name: type/minor
  color: "ff9800"
- name: type/major
  color: "f6412d"
# Uncategorized
- name: on-hold
  color: "ee0701"
