---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-atuin
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/default/atuin/app
  postBuild:
    substitute:
      APP: atuin
      APP_GID: "1000"
      APP_UID: "1000"
      PVC_NAME: atuin-data
      PVC_SIZE: 4Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  targetNamespace: default
  wait: false
