---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${PVC_NAME}"
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  # dataSourceRef:
  #   kind: ReplicationDestination
  #   apiGroup: volsync.backube
  #   name: "${APP}-bootstrap"
  resources:
    requests:
      storage: "${PVC_SIZE}"
