---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app actual
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    controllers:
      actual:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/actualbudget/actual-server
              tag: 26.7.0@sha256:e18b7fbfec6157a368fad4146563f397502e9da70a120aeaeac63b4977405d1c
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 5006
    route:
      app:
        hostnames: ["actual.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: networking
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: http
    persistence:
      data:
        existingClaim: "${PVC_NAME}"
        globalMounts:
          - path: /data
