---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: doppler
  namespace: kube-system
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-secret
            key: service-token
            namespace: kube-system
