apiVersion: v1
kind: Secret
metadata:
  name: doppler-secret
  namespace: kube-system
stringData:
  service-token: ENC[AES256_GCM,data:dW5A3IUL5VK5K8zngN3glJY1WxsqsJYGcYxJonZdhLnjEbQZ/BfR1Rn4XZE2UYqIJJSbMH/2,iv:G+qwnQ3DqQ9xNI8ugxUKDYTVXBDfbZLzo5IRRCgSnhg=,tag:7eWxRcJ02dqKMkb1hGI5kg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHhEUDBjZ2Ex
        L2E2eUY5Qmw5dnRTT2FiOXZRSzhmR2JORkFSNy81SXNOUytWL3VldmZybUZ6Ny92
        ZnltV1dBNmNSekU0S2pVL2NMU1VSK1pYV0F0b1Mra0JtU0JsKy9adXErd3BSMDFp
        dzloNDBhQytRTVZBQ2Q3L25ORWtGdk9CYUorcXpZVDcwUGZvMWFuWGZiTUxhY3FD
        ZHh0SHFqM1lNTHBBWlFaRklVOEVVM3k2b21UdUlvaU4reU1uS1BNMXFWWWZ2TTM4
        bk9odC82dWgwWUtZSVFpK1dMMWJzaXVINFRqWTNwUU1pTFZHODJ1T1VuZ3R2NHJo
        VGpzeThtLzhhQmQ2eUpPS0RXaUtlblVjM2NURjZkd2hlekRKVCtGaFVUb0djRzhC
        cm80MldtUnhZRHZoanhOL3VGeFc4ZWRhSHI5bERodFZkc08rVWZiREozeVhsUUZT
        MUhscDVJQm41WUJjemI5dkJPMWtGQklQUFpGUVhBSjdZTWIrRWJVckR5d2E3blBy
        d094MTdZS2d1U1Z5UHRoWFUyMDZBZFR1SC9PeVhmS3JoSnJ5Qy91dTd5aVRWUm9U
        Y1pJK1prbmNDVnd1dWdDVUxjTmw4TzNEb3BTR2hWYVVnQVNoTGJoZ29mdEE0M3Fr
        aXRoSldlaUd3MEtuVzNSL3dtRm9sZ1hYUTUxT2FKUnJxU1l1WHBwRVdCQmlFdkZi
        N1BabEVoVzRCNW1FZXdtOFdEUitpZzhMKzZSaGtOb3ZOWVJ1ajVPdURCYW56blhp
        SzIrM2p3VkRrS2JSK0E5bHRnb2JjTStiVDlzenZ5d3BESUdUbkFHLzdkczVOOEZY
        Y0dPRjBRWmtidURJaFdnMHQwYmZzZ2RLdThyRTlkSjc3NGx0WE44Ry9rMGpJcXhn
        VGVya2VUT0ZjQnd5ZUxMUWNnUHFVSExrNkw3V1N5Z0pzNmJ4MHc1ZFNKM240bWNC
        ODJSSzBzalo4TWtxcWZFSjVqU3c5dUkrdDd4Z1FYeTdJYysxLzNUK0lFblV6cTdo
        WDBJNGMxeHMvWFZBNjV6a2d1Z09EYTRGVDF5aHU3QmsveWF6Rzh3NEVUMDZ0U2tm
        QXN4aSs4NXBxOEQyQlZpUUZicGN3SVI5V0Q5am43VEtqc2pIRFJnYWwvbkpGclRt
        bVBOOCswNXRsYWkxOTBvd2FnTkM1TC9FYlRGMTBBR3drTlI0TnEzVVpFQTRKcFdQ
        TnUveU8zellta2hjZXBpVlkybm11OWRwbnpueUxDQmU5d21BNm8xc04xNVkxMEdJ
        WC9GNEVud3ErTFg4TkZJUXNYMkNORCt3eUdIZU9uTFc0L3ZDSWRtWHFmSVhSUzJv
        UlpOdDNoN2Y0YTZjaWZ0TU9BK1RGdklyZEU0UWFSSDhSRDJMYTBPcmdLQXNqVktZ
        d3ZDb0RPWnpyczBRWXdHZG8vSVpWMmpYb2pialdLblRZT2NPaC9rd2FqK2xSNGc0
        ZW9iRU1WYjFjOGkrYkJ1OUk5Tks5SFp4WXJzM05Kb1QwYm91SnFnT1ZidzFQbmhE
        MUlyVUJvZ3dJQ25IS3MwWWNNRHJ5QnlMdHN4SSthR1NZVW11aVdrUkZVUFh1M2U5
        elJaSWZtdDczaitkdk15alFaUHBneU9tTHhBcENjK01ybzlBRWRiQ2cxZGJtcHht
        U3BpUURoLzhKeDk3ZjRiSllHVFdTTzRVcUtOam9TUmxmZUd4UWpDcnljMmtDYVNG
        ZlA2QWdmb3ludzJxNFdSTk5mbEdkUjhqS1VqRnVQVU1VM2x6VE1YV01LMHJ3aDVj
        WWRkb2JWNm5yUzUvNTllQUpWbU4xWGhWcHdCT1VtaWtxWElkL3JIQzVKQk5naVlw
        dWpNK1htMDdDZGFwVVZQNlB4VUo2SUlzdmtDZm1LeVI0OTdYZHhCdzBIMXV0YVQ4
        UVJmcjIzT1hueld6WCt6VHdOVjJ3NzZTTzU0alhXVUZNY0VnRW1ZVWxod2tXQQoz
        aWdwU2N5L2FuM21Wa2dtbUxxKzdFVEgraGRhOXFJTERRSzFiVlVRMUlRCi0tLSBO
        cTRPMEp4QkVkTkJubVcxRzM3dktyY3ZGQ0hPWHE0RDdvM1g0T2JyQXBvChN0/AEk
        1XtJbIlpoZanxpGzE0hIrdlOsI9edAOvR2CJJoWF+CSq8h9gRR1mVjg+wf8IlLn8
        GvFzr7tDCGukuHM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1h75r99fqcjt748r72jyl8vecm32ncyxher2yqt2majrnj49502qsqu35d4868puhus4wmzfxakthvkdx05l0pt0tzx2uz7nemzuy879yevqzs2v7cau28fqhrlcfdnpjj2t7yetq3spx6aa6nsjea4qtckyn3ys3yw85rgy0lzdf8nhkqd3jp9s3u7xzu9mfr0s5z69fn65tdym9wg5cxhpwpqjqhqkvx8ytnjm7cam3z2cppq93ceny5stay6m6qcs5ua7pkc2q554mkjlc4pza6lym4wfvv065t8qr42lstd5jhfgmv2fn7jcnl6d62f9zh87x5w5y6km3chenw9u807gdt9ughvm7r2e9xextknayg8uzsft0q4gf8ey0zfym0pn335jk808rftr96pktgzmesnmmxy4qqa9n4futgtr7fx2x7wkywjgj9pgfxzm8k5gk7nuzt0azrhuqxn9l8v3phwc3lp32lpaq0xt6xgppv2xszqnrv722u99q35a4gd4kppw07sa9khetely5pa0ky7qj5jhhnqsz6av4m2enpzqgzg2x8sfj45zpas9tfr6zqjwjv98zvfn47wqjarepgz43ya5hj0d87ayhhp4vueds7neqpm6sjug36skd0q7pl32672ttzfmayhqyxnqklaa2t5yulqyzt0qjcm079vtxy59rwcnvu2vytfszzukn8zvjn9ex35gu5qwr3l4z9z7h7sf33fr6lwyyu9wffd6s9yvuxjyg82s8z6zjlusjsh3fzsmcawymnvupkctu0vppyr6mcs0yw9j8042vp2ananu5xshvx02wvkqkletvfjrgw79gxvc9cxvjsy3qfxdvcu28yrj5rz77sgkr734yhgntkjnr5h55cny6f0vqk6mmea9tl3d5d9lppke95ls2uxhzd3cqkejn9a7uzfm9jru9dtp9s5sw3p6qm6tytzuzj0sumdfyymp2cyqjv9cx44cf24h4gpgfuz4lugcy0umegczhfvrxu5ddqd5zg62c8px2e00c5dvkez0tc7fwu8fy9etx4wrh2dhf3jghyxwdzgyta22un24z9gw7z39ajly2cyessr7uq5ufvn8fn3pvls6pqugf8u5t5esr4n3ywv6x42k83dvuh6scgmuged394tyzuzfva4vxdzvztar78xrmwv0d9ee9lmjcltf4pvxmg3fqnj3jymz8mhk99y09p3skyykdypx3e5fgkpm3u68s043x0x0ayqvhfe2pcuetflmjs38fzddqpslkqcmlm7cq95etpvq7vm577ev69y33jrejvaxskrqjnwtn6eq4fpw2uut8uk9nr03xqu5t74helgzp0prj03qfek6z20w2rs35kva8wdc5q6gznk3fgxm3gf2vh9t3tssmutwz3rqrwu50vrzus3t3nvrqff7hkyyv4f88wm8z7fqyk49twvttx78f33wtxj45dgn4v5eyfmrhtsx6vnmx6k8smkt5yysjf6sfsh7zrf6gzu97uxmxqvysjy5ct9nxpwe4u4e9sds4kvjsm2rv36fjgnwwnwjz8ayldd4tu08cedglz0ddlgjgfwqrnte805t8dhg42qdydpv8y7794xfsxvwjtxek03szev3htmrkc5mxusy808spevt9ezew0mzgp7dn0df23teexuc6vr8n2qdp83arpmqkzswkqpdssj8z4gna9u6j763jfe9gc08vmj6xm4zdmea5qdrvjmxfnwpu6qlyc9v2jemerp3c8yzc920jjz5gwsgs7rys5az8zlz3w60pdsu72v6xcw56hd5xxzjxwx2e6xc6lddr3l2xntw5at90faq2hcsfd7qadmuj5z8auw47zsvux44ez40vz00z2uwecg58yz72s0z370kdf9cumfcy7s8jmlp0xcuz5vqz0swyeqes
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-20T21:09:35Z"
  mac: ENC[AES256_GCM,data:lTMUomm4qxN+mvmMqK8XtImA1MUuk3aeV2WqzFMFjmBgzwUH3N7NlBVzsTVbYsDei5Na34wUwfUD/NgghB6qNtvhrfQhXvRMW3SiW+Z25SiV25sJp9q63aEggBBgPgMTLBVwCfTliGQs+U9hjywmDCBk6Tm/y5ObXwkvY9ebQwM=,iv:wrffvZLobvNLoxlIdD1vwwwReVyd8aBIF9bMNMpijp8=,tag:L5rJbvzmTjxhYGLTmBjVTQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
