---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: synology-csi
  namespace: flux-system
spec:
  interval: 1h
  url: https://christian-schlichtherle.github.io/synology-csi-chart
