---
originRequest:
  originServerName: "external.${SECRET_DOMAIN}"

ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: https://external-ingress-nginx-controller.networking.svc.cluster.local:443
  - hostname: "*.${SECRET_DOMAIN}"
    service: https://external-ingress-nginx-controller.networking.svc.cluster.local:443
  - service: http_status:404
