---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: victoria-metrics
  values:
    fullnameOverride: victoria-metrics
    global:
      image:
        registry: quay.io
    alertmanager:
      config:
        route:
          receiver: pushover
          repeat_interval: 12h
          routes:
            - receiver: blackhole
              matchers:
                - alertname = InfoInhibitor
            - receiver: heartbeat
              matchers:
                - alertname = "Watchdog"
              group_interval: 2m
              group_wait: 0s
              repeat_interval: 2m30s
          group_by:
            - alertname
            - job
          group_interval: 5m
          group_wait: 1m
        inhibit_rules:
          - equal:
              - alertname
              - namespace
            source_matchers:
              - severity = "critical"
            target_matchers:
              - severity = "warning"
        receivers:
          - name: blackhole
          - name: heartbeat
            webhook_configs:
              - url_secret:
                  name: vmalertmanager
                  key: ALERTMANAGER_HEARTBEAT_URL
          - name: pushover
            pushover_configs:
              - html: true
                message: |-
                  {{- range .Alerts }}
                    {{- if ne .Annotations.description "" }}
                      {{ .Annotations.description }}
                    {{- else if ne .Annotations.summary "" }}
                      {{ .Annotations.summary }}
                    {{- else if ne .Annotations.message "" }}
                      {{ .Annotations.message }}
                    {{- else }}
                      Alert description not available
                    {{- end }}
                    {{- if gt (len .Labels.SortedPairs) 0 }}
                      <small>
                        {{- range .Labels.SortedPairs }}
                          <b>{{ .Name }}:</b> {{ .Value }}
                        {{- end }}
                      </small>
                    {{- end }}
                  {{- end }}
                priority: |-
                  {{ if eq .Status "firing" }}1{{ else }}0{{ end }}
                send_resolved: true
                title: >-
                  [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
                token:
                  name: vmalertmanager
                  key: ALERTMANAGER_PUSHOVER_TOKEN
                url_title: View in Alertmanager
                user_key:
                  name: vmalertmanager
                  key: PUSHOVER_USER_KEY
      route:
        enabled: true
        hostnames: ["alertmanager.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: networking
            sectionName: https
      spec:
        externalURL: "https://alertmanager.${SECRET_DOMAIN}"
        image:
          repository: quay.io/prometheus/alertmanager
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              resources:
                requests:
                  storage: 1Gi
      useManagedConfig: true
    defaultDashboards:
      defaultTimezone: browser
      grafanaOperator:
        enabled: true
        spec:
          allowCrossNamespaceImport: true
    defaultDatasources:
      grafanaOperator:
        enabled: true
        spec:
          allowCrossNamespaceImport: true
    grafana:
      enabled: false
      forceDeployDatasource: true
    kube-state-metrics:
      enabled: false
    kubeControllerManager:
      enabled: true
      endpoints: &endpoints
        - 192.168.4.10
        - 192.168.4.13
        - 192.168.4.14
      vmScrape:
        spec:
          endpoints:
            - port: http-metrics
              scheme: https
              bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              tlsConfig:
                insecureSkipVerify: true
              metricRelabelConfigs:
                - action: keep
                  sourceLabels: ["__name__"]
                  regex: "(apiserver_audit|apiserver_client|apiserver_delegated|apiserver_envelope|apiserver_storage|apiserver_webhooks|attachdetach_controller|authenticated_user|authentication|cronjob_controller|disabled_metric|endpoint_slice|ephemeral_volume|garbagecollector_controller|get_token|go|hidden_metric|job_controller|kubernetes_build|kubernetes_feature|leader_election|node_collector|node_ipam|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|pv_collector|registered_metric|replicaset_controller|rest_client|retroactive_storageclass|root_ca|running_managed|scrape_duration|scrape_samples|scrape_series|service_controller|storage_count|storage_operation|ttl_after|volume_operation|workqueue)_(.+)"
                - action: drop
                  sourceLabels: ["__name__"]
                  regex: ".*_bucket"
    kubeEtcd:
      enabled: true
      endpoints: *endpoints
      service:
        port: 2381
        targetPort: 2381
      vmScrape:
        spec:
          endpoints:
            - port: http-metrics
              scheme: http
    kubeScheduler:
      enabled: true
      endpoints: *endpoints
      vmScrape:
        spec:
          endpoints:
            - port: http-metrics
              scheme: https
              bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              tlsConfig:
                insecureSkipVerify: true
              metricRelabelConfigs:
                # Remove duplicate labels provided by k3s
                - action: keep
                  sourceLabels: ["__name__"]
                  regex: "(apiserver_audit|apiserver_client|apiserver_delegated|apiserver_envelope|apiserver_storage|apiserver_webhooks|authenticated_user|authentication|disabled_metric|go|hidden_metric|kubernetes_build|kubernetes_feature|leader_election|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|registered_metric|rest_client|scheduler|scrape_duration|scrape_samples|scrape_series|workqueue)_(.+)"
                - action: drop
                  sourceLabels: ["__name__"]
                  regex: ".*_bucket"
    kubeApiServer:
      enabled: true
      vmScrape:
        spec:
          endpoints:
            - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
              port: https
              scheme: https
              tlsConfig:
                caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                serverName: kubernetes
              metricRelabelConfigs:
                # Remove duplicate labels provided by k3s
                - action: keep
                  sourceLabels: ["__name__"]
                  regex: (aggregator_openapi|aggregator_unavailable|apiextensions_openapi|apiserver_admission|apiserver_audit|apiserver_cache|apiserver_cel|apiserver_client|apiserver_crd|apiserver_current|apiserver_envelope|apiserver_flowcontrol|apiserver_init|apiserver_kube|apiserver_longrunning|apiserver_request|apiserver_requested|apiserver_response|apiserver_selfrequest|apiserver_storage|apiserver_terminated|apiserver_tls|apiserver_watch|apiserver_webhooks|authenticated_user|authentication|disabled_metric|etcd_bookmark|etcd_lease|etcd_request|field_validation|get_token|go|grpc_client|hidden_metric|kube_apiserver|kubernetes_build|kubernetes_feature|node_authorizer|pod_security|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|registered_metric|rest_client|scrape_duration|scrape_samples|scrape_series|serviceaccount_legacy|serviceaccount_stale|serviceaccount_valid|watch_cache|workqueue)_(.+)
                # Drop high cardinality labels
                - action: drop
                  sourceLabels: ["__name__"]
                  regex: (apiserver|etcd|rest_client)_request(|_sli|_slo)_duration_seconds_bucket
                - action: drop
                  sourceLabels: ["__name__"]
                  regex: (apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket)
                - action: drop
                  sourceLabels: ["__name__"]
                  regex: ".*_bucket"
    kubelet:
      vmScrape:
        spec:
          metricRelabelConfigs:
            # Remove duplicate labels provided by k3s
            - action: keep
              sourceLabels: ["__name__"]
              regex: (apiserver_audit|apiserver_client|apiserver_delegated|apiserver_envelope|apiserver_storage|apiserver_webhooks|authentication_token|cadvisor_version|container_blkio|container_cpu|container_fs|container_last|container_memory|container_network|container_oom|container_processes|container|csi_operations|disabled_metric|get_token|go|hidden_metric|kubelet_certificate|kubelet_cgroup|kubelet_container|kubelet_containers|kubelet_cpu|kubelet_device|kubelet_graceful|kubelet_http|kubelet_lifecycle|kubelet_managed|kubelet_node|kubelet_pleg|kubelet_pod|kubelet_run|kubelet_running|kubelet_runtime|kubelet_server|kubelet_started|kubelet_volume|kubernetes_build|kubernetes_feature|machine_cpu|machine_memory|machine_nvm|machine_scrape|node_namespace|plugin_manager|prober_probe|process_cpu|process_max|process_open|process_resident|process_start|process_virtual|registered_metric|rest_client|scrape_duration|scrape_samples|scrape_series|storage_operation|volume_manager|volume_operation|workqueue)_(.+)
            - action: replace
              sourceLabels: ["node"]
              targetLabel: instance
            # Drop high cardinality labels
            - action: labeldrop
              regex: (uid)
            - action: labeldrop
              regex: (id|name)
            - action: drop
              sourceLabels: ["__name__"]
              regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
    prometheus-node-exporter:
      enabled: false
    victoria-metrics-operator:
      crds:
        cleanup:
          enabled: false
      operator:
        enable_converter_ownership: true
    vmagent:
      spec:
        extraArgs:
          promscrape.dropOriginalLabels: "true"
          promscrape.maxScrapeSize: 50MiB
          promscrape.streamParse: "true"
    vmalert:
      spec:
        extraArgs:
          external.url: "https://vmalert.${SECRET_DOMAIN}"
        datasource:
          url: http://vmauth-victoria-metrics.monitoring.svc.cluster.local:8427
      route:
        enabled: true
        hostnames: ["vmalert.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: networking
            sectionName: https
    vmauth:
      enabled: true
      spec:
        extraArgs:
          requestBufferSize: "65536"
        unauthorizedUserAccessSpec:
          url_map:
            - src_paths:
                - /api/v1/query.*
                - /api/v1/label/.*
              url_prefix: http://vmsingle-victoria-metrics.monitoring.svc.cluster.local:8428
            - src_paths:
                - /select/logsql/.*
              url_prefix: http://victoria-logs.monitoring.svc.cluster.local:9428
    vmsingle:
      route:
        enabled: true
        hostnames: ["vmsingle.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: networking
            sectionName: https
      spec:
        retentionPeriod: 90d
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 40Gi
          storageClassName: longhorn
    extraRules:
      dockerhub-rules:
        create: true
        groups:
          - name: dockerhub
            rules:
              - alert: DockerhubRateLimitRisk
                annotations:
                  summary: There are {{ $value }} containers pulling from Dockerhub. This may lead to rate limiting.
                expr: count(time() - container_last_seen{image=~"(docker.io).*",container!=""} < 30) > 100
                labels:
                  severity: critical
      oom-rules:
        create: true
        groups:
          - name: oom
            rules:
              - alert: OomKilled
                annotations:
                  summary: Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} has been OOMKilled {{ $value }} times in the last 10 minutes.
                expr: (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[10m]) == 1
                labels:
                  severity: critical
