# ---
# apiVersion: gateway.envoyproxy.io/v1alpha1
# kind: SecurityPolicy
# metadata:
#   name: authelia-ext-authz-
# spec:
#   targetRefs:
#     - group: gateway.networking.k8s.io
#       kind: HTTPRoute
#       name:
#   extAuth:
#     headersToExtAuth:
#       - accept
#       - cookie
#       - authorization
#       - proxy-authorization
#       - x-forwarded-proto
#     failOpen: false
#     http:
#       backendRefs:
#         - name: authelia
#           namespace: default
#           port: 80
#       path: /api/authz/ext-authz/
#       headersToBackend:
#         - Remote-User
#         - Remote-Groups
#         - Remote-Name
#         - Remote-Email
