---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atuin-server
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      atuin:
        containers:
          app:
            image:
              repository: ghcr.io/atuinsh/atuin
              tag: 18.16.0@sha256:5efef47edb5c069eefeb5a077181c76daaa3576c3a401de15ffddfd6042e1284
            args: ["start"]
            env:
              TZ: "${TIMEZONE}"
              ATUIN_HOST: 0.0.0.0
              ATUIN_PORT: &port "8888"
              ATUIN_OPEN_REGISTRATION: "true"
              ATUIN_DB_URI: "sqlite:///data/atuin.db"
            resources:
              requests:
                cpu: 10m
                memory: 30Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: ${APP_UID}
        runAsGroup: ${APP_GID}
        fsGroup: ${APP_GID}
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: atuin
        ports:
          http:
            port: *port
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: "atuin.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        existingClaim: "${PVC_NAME}"
        globalMounts:
          - path: /data
