---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    template:
      data:
        GF_SECURITY_ADMIN_USER: "{{ .ADMIN_USER }}"
        GF_SECURITY_ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        # ADMIN_EMAIL: "{{ .ADMIN_EMAIL }}"
  dataFrom:
    - extract:
        key: GRAFANA
