apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
  namespace: flux-system
stringData:
  token: ENC[AES256_GCM,data:wPf2UW2HAvaf1HwxxxiRVAIUS5OjLfVH,iv:6K05GeMaiq60OkGlnEDt1KxxHlgBUJdL1QKKJs5HfJc=,tag:pQlZ2czvG4xlm9HkCuBhfQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHRwdGpjODg2
        Zk9TYk5BNTY5QlFGVTNkM3BhZVdPWExhV1lzZXB4aW5Qd1hIbzMyUk80Yi8rU0tv
        R2RoRTR0WTNMUU0rcnJabEJsQ2R2VE41czhwNEVLb1dwREZGWTVJOC9OWW1OY0l5
        dWVGM1ZvUTlOU25YTW01RlpYVmp3WTJEYkxuT1RpTkJXeVZpaG1xT1l4VUx1N052
        WDNMaXlOTms3TG1nZkJ5aWVsZDJrM0xZTUFOY2FrL1NrVUtCMEh2YlhIem1yRjg4
        c2NrOGdzZWpOSE5pRjNXWEFkQWttYWFnTGg1azRMNG5ZWC8xOWNrNERpTFZDc0g4
        SWVjVEV3YnBmZ0h3VzVtZkVvbDdCUjMxanBqVnJnd1kxMklDeEkwRE82SUhZNDNX
        N2ZHMitrUWNHZkpsTW9ISW5RbjVWaWcvc0lGOHEySmFQTmwxTlVDWHRBL2JHblNG
        WUt1RC9LaDB4YVBoWVY1WGJYbU5XVlVjK3c4czFsemloeDVzOW4wZ1pjOWdLTVZz
        TVBtQXB5cGJLSHY1Q0NkOGkxWTlueldiOEM0SDBkM3pRMENoeXNwUjY1Wm04Q21C
        RmtsSmx1TXBqaTR1aEloNXk0UjBiekpEdlZzYmsyZVBMbWd2UmhyYTdueUxFSk1u
        YW5KK3lDQzhQaVY2NDlvVUI0UXlhZENHa3BpMkdsOHBXUUQxNGFlbEZZUHpEcFVZ
        S2NTZlgwc05LajNleDF6Nkw2ZFEyWkpjUUN6OXJ4ZWZFSSt0cUZKSEJob08zNEtK
        dzhpQWlvUld0Z1RtcDlmYWJKcExFTk5CcUZ6TjMvMG5sRXI1QkVTR1JreU1pbEc3
        VE5Ga1RGNkkra2Zlb0NRYkhxUVo5OGNlRlZEUTBDMk5hYVdBZ3VQZTBqcHZoUXJl
        U09zMXdlNEtNVElQS1pIYmpHa3d2Q2hZek5kWU5CQ1k2K1BkK2ZKY1ZDTGdjZUxB
        ZFFvQWNFM2tWTktzKzJKcWVCYTRPajEwZkVYMk43RERhZk5NSzVNeGxLMVNvNzE1
        cklEOTkyZkNZdmJyVnovbnp3TUxkdFZFeEY4YytMckg2a0grcldqQVh4QWJvY0Jx
        M1drUzh2dW95d1Vwb0N3STEwRk95Szd1bzg4UTZySjhlOXRHVlYzaDBzWS81ZEhi
        WjU0MGMzVHQ5ejNDZjdLMkZSU2hZOUZlZU8xSGxJRUtid0UrY01BN3RudGQyd0I2
        c2EyemNnWjJ3L2hnQXovTWI0VDBmc1dpYXIwckN3MGxLTlIxbElzVmJRajNxYlUx
        V1lacFIwaG1FTjhNWWQ0ZFE3V01FYnJlVWZJTVU4aFBUZG5sTnFONWRQbDc0b2dW
        dmJ5MnRvZHBCM2Q5eXlNM0FnaTZMRFp4YlJRR1lLUlJYcWdlTnBuUmpRU1JNRU42
        V1l3a1Jma2NOUU1KZXFIditqYjdzZWttckRVVy9TbEtFd3RSUktMenpGb1FEaXlz
        Y3g4emd2Mm9uQTFjazdraXdxcE1WSkt6T1hhNmE1M2E0MnNyUGJTYWw1Rk8vTDhV
        alJKbUxSK1pSRnhhSmd3cGgzcVlmUk01aEU1UzM0WWcrYmpNZlB2dDV1VXkrbzJV
        RWdQcXdnV0hQUXBlNXA5V3FwVzJ5YXNaM2h4NmhLUVFzUnUrdXJ2ODRIMXlTc0FJ
        RHJlRTZGRDlHMS9WM2Nma0RsK0V0VHd4b1JVcXhjcnpTU0Q5UkNuRytDRlR3UjhS
        bjQ0d1Z6QzE1dHEraGRqMGp3QWl1aWNYTVlMaWJpWnZNZ3pKVDNxaDVwb1JMUVJu
        MW5HUWhjL2FRbDhXd0VqU1dmWHVTM0t0cW8wZ2dubHB0NlVOb1VwRVhmakh1Rndx
        Ym9FQi9MWCtjdjB3WDJGM1pMMDB3UFVqVndoTXkvMmExY3NTczRDV1lVRDYwVEpU
        T3FINXU3SFhLMGdZcElQck9ZM2dWc0ZMQWFWRnBaUWlFK0ZQSG9SQmhkbGxLQQpy
        RXd3aHcxTGkwTy9JMXF1c25BOEVYNG4wT1NiSEFQZ3Brby9sR3hqL0w4Ci0tLSBj
        aU4zY0pBa0tHcWk2cElwWnNpVjNQYjFhVGt5aDY3SDdyS2hieU1FNldrCsgj8JOS
        4Sy7f3DsCl+vAZKvUKUtCStWdJI4LYxybgTPCj/cr7RkpalCVSCcBhVADOW8FpOS
        VF19fdypDyT+8q0=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1h75r99fqcjt748r72jyl8vecm32ncyxher2yqt2majrnj49502qsqu35d4868puhus4wmzfxakthvkdx05l0pt0tzx2uz7nemzuy879yevqzs2v7cau28fqhrlcfdnpjj2t7yetq3spx6aa6nsjea4qtckyn3ys3yw85rgy0lzdf8nhkqd3jp9s3u7xzu9mfr0s5z69fn65tdym9wg5cxhpwpqjqhqkvx8ytnjm7cam3z2cppq93ceny5stay6m6qcs5ua7pkc2q554mkjlc4pza6lym4wfvv065t8qr42lstd5jhfgmv2fn7jcnl6d62f9zh87x5w5y6km3chenw9u807gdt9ughvm7r2e9xextknayg8uzsft0q4gf8ey0zfym0pn335jk808rftr96pktgzmesnmmxy4qqa9n4futgtr7fx2x7wkywjgj9pgfxzm8k5gk7nuzt0azrhuqxn9l8v3phwc3lp32lpaq0xt6xgppv2xszqnrv722u99q35a4gd4kppw07sa9khetely5pa0ky7qj5jhhnqsz6av4m2enpzqgzg2x8sfj45zpas9tfr6zqjwjv98zvfn47wqjarepgz43ya5hj0d87ayhhp4vueds7neqpm6sjug36skd0q7pl32672ttzfmayhqyxnqklaa2t5yulqyzt0qjcm079vtxy59rwcnvu2vytfszzukn8zvjn9ex35gu5qwr3l4z9z7h7sf33fr6lwyyu9wffd6s9yvuxjyg82s8z6zjlusjsh3fzsmcawymnvupkctu0vppyr6mcs0yw9j8042vp2ananu5xshvx02wvkqkletvfjrgw79gxvc9cxvjsy3qfxdvcu28yrj5rz77sgkr734yhgntkjnr5h55cny6f0vqk6mmea9tl3d5d9lppke95ls2uxhzd3cqkejn9a7uzfm9jru9dtp9s5sw3p6qm6tytzuzj0sumdfyymp2cyqjv9cx44cf24h4gpgfuz4lugcy0umegczhfvrxu5ddqd5zg62c8px2e00c5dvkez0tc7fwu8fy9etx4wrh2dhf3jghyxwdzgyta22un24z9gw7z39ajly2cyessr7uq5ufvn8fn3pvls6pqugf8u5t5esr4n3ywv6x42k83dvuh6scgmuged394tyzuzfva4vxdzvztar78xrmwv0d9ee9lmjcltf4pvxmg3fqnj3jymz8mhk99y09p3skyykdypx3e5fgkpm3u68s043x0x0ayqvhfe2pcuetflmjs38fzddqpslkqcmlm7cq95etpvq7vm577ev69y33jrejvaxskrqjnwtn6eq4fpw2uut8uk9nr03xqu5t74helgzp0prj03qfek6z20w2rs35kva8wdc5q6gznk3fgxm3gf2vh9t3tssmutwz3rqrwu50vrzus3t3nvrqff7hkyyv4f88wm8z7fqyk49twvttx78f33wtxj45dgn4v5eyfmrhtsx6vnmx6k8smkt5yysjf6sfsh7zrf6gzu97uxmxqvysjy5ct9nxpwe4u4e9sds4kvjsm2rv36fjgnwwnwjz8ayldd4tu08cedglz0ddlgjgfwqrnte805t8dhg42qdydpv8y7794xfsxvwjtxek03szev3htmrkc5mxusy808spevt9ezew0mzgp7dn0df23teexuc6vr8n2qdp83arpmqkzswkqpdssj8z4gna9u6j763jfe9gc08vmj6xm4zdmea5qdrvjmxfnwpu6qlyc9v2jemerp3c8yzc920jjz5gwsgs7rys5az8zlz3w60pdsu72v6xcw56hd5xxzjxwx2e6xc6lddr3l2xntw5at90faq2hcsfd7qadmuj5z8auw47zsvux44ez40vz00z2uwecg58yz72s0z370kdf9cumfcy7s8jmlp0xcuz5vqz0swyeqes
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-20T21:09:31Z"
  mac: ENC[AES256_GCM,data:ufuEYJj8OAG0YPits6NqUps1N8E3V9FjhZH6lPaOuTbSdWyi/efRjZ8rc4T+S/G41g4PBEHBkE78nGD8ZlYXRrVosIl1vg//4767Zvo6G9FpVM6MrhhHMAdbcaxfvOoGVAOMQ3fvLte7g0hpWpXR6nRuJpLXHH8Sf/qca4z/QjA=,iv:7JfnJ0rIQ77ptwUN/kXrjyI+7ZYrBhOWcG4CFid2ru0=,tag:eHt48DZ0wxMu+bYlC13a2A==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
