---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: synology-csi
      version: 0.10.1
      sourceRef:
        kind: HelmRepository
        name: synology-csi
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    clientInfoSecret:
      create: false
      name: synology-csi-secret
    installCSIDriver: false
    storageClasses: {}
    # created in snapshot-controller helmrelease
    volumeSnapshotClasses: null
