---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-csi
provisioner: csi.san.synology.com
parameters:
  fsType: ext4
  location: /volume1
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
