---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-ext
  namespace: longhorn-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .LONGHORN_AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .LONGHORN_AWS_SECRET_ACCESS_KEY }}"
        AWS_ENDPOINTS: "{{ .LONGHORN_AWS_ENDPOINTS }}"
  dataFrom:
    - extract:
        key: LONGHORN

