---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-prometheus-servicemonitor
  namespace: longhorn-system
  labels:
    name: longhorn-prometheus-servicemonitor
spec:
  endpoints:
    - port: manager
      relabelings:
        - sourceLabels: [__meta_kubernetes_node_name]
          targetLabel: instance
  selector:
    matchLabels:
      app: longhorn-manager
