---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-cache
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  dataLocality: disabled
  numberOfReplicas: "1"
