---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-atuin-server
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app atuin-server
  path: ./kubernetes/apps/default/atuin-server/app
  postBuild:
    substitute:
      APP: *app
      APP_UID: "1000"
      APP_GID: "1000"
      PVC_NAME: atuin-data
      PVC_SIZE: 4Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  timeout: 5m
