---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-status-secret
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    template:
      data:
        token: "{{ .TOKEN_COMMIT_STATUS }}"
  dataFrom:
    - extract:
        key: FLUX
