---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    template:
      data:
        api-token: "{{ .API_TOKEN }}"
  dataFrom:
    - extract:
        key: CLOUDFLARE
