---
# Not managed by doco-cd

services:
  app:
    container_name: doco-cd
    environment:
      DEPLOY_CONFIG_BASE_DIR: ./docker/vps/
      LOG_LEVEL: info
      POLL_CONFIG: |-
        - url: https://github.com/lkmgr/homelab.git
          reference: refs/heads/main
          interval: 300
      TZ: Europe/Berlin
      SOPS_AGE_KEY_FILE: /run/secrets/sops_age_key
    healthcheck:
      test: ["CMD", "/doco-cd", "healthcheck"]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    image: ghcr.io/kimdre/doco-cd:0.110.1@sha256:cd491cf9ec09e39f0e690a418e8a5e2c5d631544d6af8f879f4de8978b847af1
    restart: unless-stopped
    secrets:
      - sops_age_key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
secrets:
  sops_age_key:
    file: /opt/docker/doco-cd/sops_age_key.txt
volumes:
  data: {}
