---
# Not managed by doco-cd

services:
  app:
    container_name: doco-cd
    environment:
      DEPLOY_CONFIG_BASE_DIR: ./docker/vps/
      LOG_LEVEL: info
      POLL_CONFIG: |-
        - url: https://github.com/lkmgr/homelab.git
          reference: refs/heads/main
          interval: 300
      TZ: Europe/Berlin
      SOPS_AGE_KEY_FILE: /run/secrets/sops_age_key
    healthcheck:
      test: ["CMD", "/doco-cd", "healthcheck"]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3
    image: ghcr.io/kimdre/doco-cd:0.121.0@sha256:c07f6d0b0df5026ce67708bfda7ff26e0e645c284914dd8be3a9b8277375603b
    restart: unless-stopped
    secrets:
      - sops_age_key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
secrets:
  sops_age_key:
    file: /opt/docker/doco-cd/sops_age_key.txt
volumes:
  data: {}
