---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./external.yaml
  - ./internal.yaml
configMapGenerator:
  - name: common-values
    files:
      - values.yaml=common-values.yaml
configurations:
  - kustomizeconfig.yaml
