---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smartctl-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: smartctl-exporter
  values:
    serviceMonitor:
      enabled: true
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: instance
    prometheusRules:
      enabled: true
      rules:
        smartCTLDeviceMediaErrors:
          for: 3m
        smartCTLDeviceCriticalWarning:
          for: 3m
        smartCTLDeviceAvailableSpareUnderThreshold:
          for: 3m
        smartCTLDeviceStatus:
          for: 3m
        smartCTLDInterfaceSlow:
          for: 3m
        smartCTLDDeviceTemperature:
          for: 3m
