---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smartctl-exporter
spec:
  interval: 1h
  chart:
    spec:
      chart: prometheus-smartctl-exporter
      version: 0.16.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    serviceMonitor:
      enabled: true
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: instance
    prometheusRules:
      enabled: true
      rules:
        smartCTLDDeviceTemperature:
          enabled: true
          alert: SmartCTLDDeviceTemperature
          expr: smartctl_device_temperature{temperature_type="current"} > 65
          for: 1m
          annotations:
            summary: Device has temperature higher than 65°C
            description: Device {{ $labels.device }} on instance {{ $labels.instance }} has temperature higher than 65°C
          labels:
            severity: warning
