---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-ipaddresspool
  namespace: metallb-system
spec:
  addresses:
    - "${METALLB_LB_RANGE}"
  autoAssign: false
  avoidBuggyIPs: true
