---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: go2rtc-secret
  namespace: default
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    template:
      engineVersion: v2
      data:
        go2rtc.yaml: |
          api:
            listen: ":1984"
            # username: "admin"
            # password: "{{ .GO2RTC_STREAM_PASSWORD }}"
          rtsp:
            listen: ":554"
            username: "stream"
            password: "{{ .GO2RTC_STREAM_PASSWORD }}"
            default_query: "video"
          webrtc:
            listen: ":80"
          streams:
            c100:
              - {{ .GO2RTC_C100_RTSP_URL }}
  dataFrom:
    - extract:
        key: GO2RTC
