---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: go2rtc
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: alexxit/go2rtc
              tag: 1.9.8
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      main:
        controller: main
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          external.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
          external-dns.alpha.kubernetes.io/hostname: "go2rtc.${SECRET_DOMAIN}"
          io.cilium/lb-ipam-ips: "${VIP_GO2RTC}"
        ports:
          webrtc:
            port: 80
            protocol: UDP
          rtsp:
            port: 554
          api:
            port: 1984
    persistence:
      config:
        name: go2rtc-secret
        type: secret
        advancedMounts:
          main:
            main:
              - path: /config/go2rtc.yaml
                # readOnly: true
                subPath: go2rtc.yaml
