---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}"
spec:
  sourcePVC: "${PVC_NAME}"
  trigger:
    schedule: "0 * * * *"
  restic:
    repository: "${APP}-volsync-secret"
    pruneIntervalDays: 7
    retain:
      hourly: 24
      daily: 7
      weekly: 4
    copyMethod: Snapshot
    cacheCapacity: 1Gi
    # cacheStorageClassName: longhorn-cache
    cacheStorageClassName: openebs-hostpath
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: longhorn-cache
    volumeSnapshotClassName: longhorn-snapshot
    moverSecurityContext:
      runAsUser: ${APP_UID:-1000}
      runAsGroup: ${APP_GID:-1000}
      fsGroup: ${APP_GID:-1000}
