---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weave-gitops-secret
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: cluster-user-auth
    template:
      data:
        username: admin
        # Create password with `gitops get bcrypt-hash`
        password: "{{ .WEAVE_GITOPS_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: WEAVE_GITOPS
