---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  uid: alertmanager
  datasource:
    name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager-operated.monitoring.svc.cluster.local:9093
    jsonData:
      implementation: prometheus
