---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: volsync-mover-jitter
spec:
  policyName: volsync-mover-jitter
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionPolicy
metadata:
  name: volsync-mover-jitter
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: ["batch"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["jobs"]
  matchConditions:
    - name: has-volsync-job-name-prefix
      expression: >
        object.metadata.name.startsWith("volsync-src-")
    - name: has-volsync-created-by-labels
      expression: >
        object.metadata.labels["app.kubernetes.io/created-by"] == "volsync"
  failurePolicy: Fail
  reinvocationPolicy: IfNeeded
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: >
          [
            JSONPatch{
              op: "add", path: "/spec/template/spec/initContainers",
              value: []
            },
            JSONPatch{
              op: "add", path: "/spec/template/spec/initContainers/-",
              value: Object.spec.template.spec.initContainers{
                name: "jitter",
                image: "docker.io/library/busybox:1.38.0@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d",
                imagePullPolicy: "IfNotPresent",
                command: ["sh", "-c", "sleep $(shuf -i 0-600 -n 1)"]
              }
            }
          ]
