apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:GT8XORcGVwYJNQzgoFpNEUfz88+I,iv:QIBkyjMZjVn0qhbxLg6ctUKxPXhQQdMHTmpcClu6Mok=,tag:HX0Ki9egazulKos+fYHaIw==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:4Au9n8uOQPE=,iv:HXFjWAhVvJEFRWBKQ4Wh3VFW97RCXZgsFch4Z9lgXs0=,tag:I2av0g8JxaGK4X2GknKxQA==,type:str]
  CF_TUNNEL_ID: ENC[AES256_GCM,data:UneqqTFi8oGO3y3Gin1iLTrlquvOaMAeD7MWvWR+aqtgGOYY,iv:l+O4rws/AdmfuUES5wS7iR4cx3Wve522cQyQPFybP6A=,tag:g7LpP/F5YGv3e5MFr5Q0TA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG5pc0VETWxk
        RVZzQi9oZWhQTHFFNDNvYlNUZFQ0Y2NxZmdwd2t3cUlUY05uSUpmZUplQUZ0S0I5
        bGVoRDJTTEpXaVVURy90WlNNMTBpTWtkZmVJTExHemIvLzIxNWRJM1ZvUE9LKzIx
        NjhmSHZvMjNDdTFJekRFR3RVZGFqRk5xYWVGR0JKRy95Q3RxMUNLSnU0WTh6SXMz
        NkM0MjJ3bVVJc012ZjVoaHpLRmNEWFpMa1hXSG1JaWZNYW80YVY5Zkd4V0hyYnFz
        QVNteHoxdGdwcENHZURycFFsS0hBRCtLUmlHOGY1dUJaaXArTXJMSTJUS01vTC95
        K2dSZU1veG9WUVoycXplMmxWbHdqdzlLV0cwTllmMkRBaVFTc0FKOEt1RHdHN09J
        L2wwbExFdDlGcTk5OVNvQkVMbE5tRDMxUjE0UTM2RFRFaXdVMDZ4RytqUlJseWhp
        bkx3bG52d2JWMnhHUmxZMkVLNFdXcktubEQxRlBQY2d1ZVgzcFVOSFhsaWRGbXdU
        TTRoVkF5YzNtYjVFOGlOZFhmekl5ay83Z004Kys5bmdhMWROb2Q5eDJkMm40ZGFZ
        ODVSaSszY1A0RzFoekR6eFJGbTJnaERIWmgrc0kyUmdoRHVPYllTSGV6WFowN01U
        cnhsOS9BTHgxazBpTVpCTHNSSk1lR2J3a2dQdmZ1b1JzaiswMldPcElLbkVyTk5Z
        QmRlQ3JLK0gzU1JGQkFkWmFIbENxU2RyM2ltam5UV1BYdFdXQ3R0TFZ1YVdtWGRj
        WkVuQmdpVkhEWVhHaE0yQ3JlaWhMUGV2SzM5ZWtvUFZSZjYrMFp5OWJ0K0s3ZWx4
        SjY1OUx3Q201OE84U3JZYVRjSmMwaWx0aWVtcTNLYzVUM2MyNmYrSmpaWXMyY0dC
        Nmp6d1dhdFJLQ3NEa1dzdUFqNVpHTUx4MnVSRTlPR2dyTUNhNFdqL1VyTUJWUGxO
        Q0FvQVdPR2VFVFc4bkMzZ2Y4RkxsOEs1aDg0K25KVlJJQXVzUEZnR2hFb0JPZ0NS
        UGllVmxWRCtOZ2RVTXZVblkxRFU1UFBxMmJ4S1d6SWlEWlUwb2FsOGJKc0JaQkhs
        Qmw3bEVrWGJ0bzFGR2R4YjZxb3hLcllNMzhqVDhBRVJFT25HQWZ1Z0NUVXU5OFdV
        RVN2TGZvaTdvYzZ0K1FrRng2Zkpia2tVQ3VBT2xnMmlHLzhKd3pSYkxDd0JsS244
        RktYMFgzZ3dnQkIvZFBQM2k1SE1jaHV6OUtVTUhpaytBalIrUE1RUERJYk9wZ28x
        NlVlNTVwWThzeko1bjNZcFJaNEI2MFplL1dIRDNJbDQ4NFVVU0wvNXpod2p2ZjVE
        R3VTNXRXZS9GUXJQRWd4dlRGMEx6WENsTlJPOUF4TTR0Y2s5ZEJIczg4M1p1NG9R
        T0s1Rm1Cb0tmbmhFQVM1NEdYR3V2RUYwZ25zeEJBVktWcnB0VE5LTjhSQ2dKSG83
        M2luWG11RkhOT3piUXc3a2tPbEVrNHJObU1FeSsvVWZ5NE1wK1A5alJwWHplSktN
        aHdGZTFQRUV1VTRURzdYR3hnZ3pETnNPUjYrZjNLczQ3Z2l0QzkrZlJqT25acTZ6
        cDQ2UHNPdDNNN2dFbWJheWdzRkVCYld4Z1ZuNUtHK2pHSWhnRENUeE5aV0MyZWhU
        RHpkc2dDQ2FpWmJNVDg1UkZYaURPSHg4UUovTUZiWTcrdnZLMVFDMGVWN0lCa3o2
        Y1Vxd1RXQUtvUDBtY2lJNFhDODYrUkVlKzlTSGJ2dzJNaVQ2aEtEZVAyUXd0Q2J1
        Z0RCVExMUU0za2FlVTlFQ2pJNEZEMUo1aExGLzFkOVlNdVUzQW5jRUZRbFdIdXhU
        czZNbThPaWpCR044SDA2NnJhRVpMWWFocEJKN2hKVXkvNTBJY21IeFBwOHE3UitZ
        QnVnSC9MaEdLL29HK2xqSTVBL3BQb3hzUFNUbUQyMVZCdUdsUDVQaFkxczVVUQpy
        T0ExeXg0aWMyZXdZc2ZoeTR0dzEvaU1FTDViS3J6L2xldEE5bVcvUnRBCi0tLSAr
        L3FHMzRhbjNaVTJBV1N2d1pYeU5KTkZKcDdJOEFnclRrbnJyWEVkZ25JCvpwJZON
        XK6f2u0zxQTOIynqnbhtkqivUykzRMHo4TbgXmF893bw685HKN214ANJO2ztVRlY
        y2rvLze4I3VKqs4=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq1h75r99fqcjt748r72jyl8vecm32ncyxher2yqt2majrnj49502qsqu35d4868puhus4wmzfxakthvkdx05l0pt0tzx2uz7nemzuy879yevqzs2v7cau28fqhrlcfdnpjj2t7yetq3spx6aa6nsjea4qtckyn3ys3yw85rgy0lzdf8nhkqd3jp9s3u7xzu9mfr0s5z69fn65tdym9wg5cxhpwpqjqhqkvx8ytnjm7cam3z2cppq93ceny5stay6m6qcs5ua7pkc2q554mkjlc4pza6lym4wfvv065t8qr42lstd5jhfgmv2fn7jcnl6d62f9zh87x5w5y6km3chenw9u807gdt9ughvm7r2e9xextknayg8uzsft0q4gf8ey0zfym0pn335jk808rftr96pktgzmesnmmxy4qqa9n4futgtr7fx2x7wkywjgj9pgfxzm8k5gk7nuzt0azrhuqxn9l8v3phwc3lp32lpaq0xt6xgppv2xszqnrv722u99q35a4gd4kppw07sa9khetely5pa0ky7qj5jhhnqsz6av4m2enpzqgzg2x8sfj45zpas9tfr6zqjwjv98zvfn47wqjarepgz43ya5hj0d87ayhhp4vueds7neqpm6sjug36skd0q7pl32672ttzfmayhqyxnqklaa2t5yulqyzt0qjcm079vtxy59rwcnvu2vytfszzukn8zvjn9ex35gu5qwr3l4z9z7h7sf33fr6lwyyu9wffd6s9yvuxjyg82s8z6zjlusjsh3fzsmcawymnvupkctu0vppyr6mcs0yw9j8042vp2ananu5xshvx02wvkqkletvfjrgw79gxvc9cxvjsy3qfxdvcu28yrj5rz77sgkr734yhgntkjnr5h55cny6f0vqk6mmea9tl3d5d9lppke95ls2uxhzd3cqkejn9a7uzfm9jru9dtp9s5sw3p6qm6tytzuzj0sumdfyymp2cyqjv9cx44cf24h4gpgfuz4lugcy0umegczhfvrxu5ddqd5zg62c8px2e00c5dvkez0tc7fwu8fy9etx4wrh2dhf3jghyxwdzgyta22un24z9gw7z39ajly2cyessr7uq5ufvn8fn3pvls6pqugf8u5t5esr4n3ywv6x42k83dvuh6scgmuged394tyzuzfva4vxdzvztar78xrmwv0d9ee9lmjcltf4pvxmg3fqnj3jymz8mhk99y09p3skyykdypx3e5fgkpm3u68s043x0x0ayqvhfe2pcuetflmjs38fzddqpslkqcmlm7cq95etpvq7vm577ev69y33jrejvaxskrqjnwtn6eq4fpw2uut8uk9nr03xqu5t74helgzp0prj03qfek6z20w2rs35kva8wdc5q6gznk3fgxm3gf2vh9t3tssmutwz3rqrwu50vrzus3t3nvrqff7hkyyv4f88wm8z7fqyk49twvttx78f33wtxj45dgn4v5eyfmrhtsx6vnmx6k8smkt5yysjf6sfsh7zrf6gzu97uxmxqvysjy5ct9nxpwe4u4e9sds4kvjsm2rv36fjgnwwnwjz8ayldd4tu08cedglz0ddlgjgfwqrnte805t8dhg42qdydpv8y7794xfsxvwjtxek03szev3htmrkc5mxusy808spevt9ezew0mzgp7dn0df23teexuc6vr8n2qdp83arpmqkzswkqpdssj8z4gna9u6j763jfe9gc08vmj6xm4zdmea5qdrvjmxfnwpu6qlyc9v2jemerp3c8yzc920jjz5gwsgs7rys5az8zlz3w60pdsu72v6xcw56hd5xxzjxwx2e6xc6lddr3l2xntw5at90faq2hcsfd7qadmuj5z8auw47zsvux44ez40vz00z2uwecg58yz72s0z370kdf9cumfcy7s8jmlp0xcuz5vqz0swyeqes
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-20T21:09:28Z"
  mac: ENC[AES256_GCM,data:FASn5jHQw5r8QoMseb4j9bSInss8FF7KdultORde5XfbtseGUY9zFOwF8CMKBNMgd9dPVNdl1MHKgmoPwju9nPbsK7gYa78U6vMmwB8SPIdvQnZDL6QwoVayqdLfPNICxDAjdZaZivpKEKHhG7iFFfAVXucFpfSNay9zLJNzqiM=,iv:0wC9baCibpRXksimrEgKlBOovBOGSRePCkKWM6BFTjw=,tag:0QEJI4sM73IOdM3ZYV9p1A==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
