---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cert-manager
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/cert-manager/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  targetNamespace: cert-manager
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cert-manager-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cert-manager
    - name: cluster-apps-external-secrets-stores
  healthCheckExprs:
    - apiVersion: cert-manager.io/v1
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      kind: ClusterIssuer
  interval: 1h
  path: ./kubernetes/apps/cert-manager/cert-manager/issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  targetNamespace: cert-manager
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cert-manager-certificates
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cert-manager-issuers
  healthCheckExprs:
    - apiVersion: cert-manager.io/v1
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      kind: Certificate
  interval: 1h
  path: ./kubernetes/apps/cert-manager/cert-manager/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  targetNamespace: cert-manager
  wait: true
