---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: open-webui-secret
    template:
      data:
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        WEBUI_SECRET_KEY: "{{ .WEBUI_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: OPEN_WEBUI
