---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: thanos
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  uid: prometheus
  datasource:
    name: Prometheus
    type: prometheus
    access: proxy
    url: http://thanos-query-frontend.monitoring.svc.cluster.local:9090
    isDefault: true
    jsonData:
      prometheusType: Thanos
