---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-esphome
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app esphome
  interval: 30m
  path: ./kubernetes/apps/default/esphome/app
  postBuild:
    substitute:
      APP: *app
      PVC_NAME: esphome-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  targetNamespace: default
  timeout: 5m
  wait: false
