---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: cloudflared-secret
    template:
      data:
        credentials.json: |
          {
            "AccountTag": "{{ .ACCOUNT_TAG }}",
            "TunnelSecret": "{{ .TUNNEL_SECRET }}",
            "TunnelID": "${CF_TUNNEL_ID}"
          }
  dataFrom:
    - extract:
        key: CLOUDFLARE
