---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terminus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    template:
      data:
        APP_SECRET: "{{ .TERMINUS_APP_SECRET }}"
        POSTGRES_PASSWORD: "{{ .TERMINUS_POSTGRES_PASSWORD }}"
        DATABASE_URL: "postgres://terminus:{{ .TERMINUS_POSTGRES_PASSWORD }}@terminus-postgres:5432/terminus"
  dataFrom:
    - extract:
        key: TERMINUS
