---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app libretranslate
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      libretranslate:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/libretranslate/libretranslate
              tag: v1.9.6@sha256:1de2d7056bb8ad607a412f4563d9abe324ff632b43b5be9428bcc8e213aebb32
            # env:
            #   # LT_UPDATE_MODELS: "true"
            #   LT_LOAD_ONLY: "en,de"
    service:
      app:
        controller: *app
        ports:
          http:
            port: 5000
    route:
      app:
        hostnames: ["translate.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: networking
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: http
    persistence:
      models:
        existingClaim: libretranslate-models
        globalMounts:
          - path: /home/libretranslate/.local
