---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: libretranslate-models
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
