---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-ext
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    template:
      data:
        REDIS_PASSWORD: "{{ .REDIS_PASSWORD }}"
  dataFrom:
    - extract:
        key: REDIS
