---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  data:
    - remoteRef:
        key: AUTHELIA_CONFIG
      secretKey: configuration.yaml
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-users
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  data:
    - remoteRef:
        key: AUTHELIA_USERS
      secretKey: users.yaml
