---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-auth-1
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    template:
      data:
        TS_AUTHKEY: "{{ .TAILSCALE_OAUTH_K8S_OPERATOR_CLIENT_SECRET_1 }}?preauthorized=true"
  dataFrom:
    - extract:
        key: TAILSCALE
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-auth-2
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    template:
      data:
        TS_AUTHKEY: "{{ .TAILSCALE_OAUTH_K8S_OPERATOR_CLIENT_SECRET_2 }}?preauthorized=true"
  dataFrom:
    - extract:
        key: TAILSCALE
