---
kubernetes:
  vars:
    ansible_user: kube
  children:
    controllers:
      hosts:
        helios:
          ansible_host: 192.168.4.10
        volt:
          ansible_host: 192.168.4.13
        arc:
          ansible_host: 192.168.4.14
