---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: config
spec:
  telemetry:
    metrics:
      prometheus: {}
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        container:
          image: mirror.gcr.io/envoyproxy/envoy:v1.39.3@sha256:dd85940439de19a0b6ae8419610363ea0ad351d9a994ea007161c206ec1e1865
          resources:
            requests:
              cpu: 20m
              memory: 200Mi
            limits:
              memory: 1Gi
      envoyService:
        externalTrafficPolicy: Local
