---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: config
spec:
  telemetry:
    metrics:
      prometheus: {}
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        container:
          image: mirror.gcr.io/envoyproxy/envoy:v1.39.2@sha256:460f8c329f24b2e1c7c5af64cb314a6f351ad1c262ba77b135ac46b35ebd5f85
          resources:
            requests:
              cpu: 20m
              memory: 200Mi
            limits:
              memory: 1Gi
      envoyService:
        externalTrafficPolicy: Local
