---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app baikal
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      baikal:
        containers:
          app:
            image:
              repository: docker.io/ckulka/baikal
              tag: 0.10.1-nginx@sha256:434bdd162247cc6aa6f878c9b4dce6216e39e79526b980453b13812d5f8ebf4b
            env:
              APPLY_HOME_ASSISTANT_FIX: "true"
    defaultPodOptions:
      securityContext:
        # runAsNonRoot: true
        # runAsUser: ${APP_UID}
        # runAsGroup: ${APP_GID}
        fsGroup: ${APP_GID}
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80
    route:
      app:
        hostnames: ["baikal.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: networking
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: http
    persistence:
      data:
        existingClaim: "${PVC_NAME}"
        globalMounts:
          - path: /var/www/baikal/Specific
            subPath: Specific
          - path: /var/www/baikal/config
            subPath: config
