---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-open-webui
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/default/open-webui/app
  postBuild:
    substitute:
      APP: open-webui
      PVC_NAME: open-webui
      PVC_SIZE: 5Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  targetNamespace: default
  wait: false
