---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
  namespace: volsync-system
spec:
  interval: 15m
  chart:
    spec:
      chart: volsync
      version: 0.12.0-rc.2
      sourceRef:
        kind: HelmRepository
        name: backube
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  dependsOn:
    - name: snapshot-controller
      namespace: kube-system
  values:
    manageCRDs: true
    replicaCount: 1
    metrics:
      disableAuth: true
